### PR TITLE
add trimmed versions of pokemon-gen8 with transparent pixels removed

### LINKED ISSUE #75: Sprites with transparent pixels trimmed?
Wondering if it's possible to have the new sprites with the transparent pixels cropped out. I understand that having them all conform to a standard of 68 by 56 pixels makes sense for a lot of use cases, but trying to use them in Google Sheets makes a lot of sprites tiny and hard to see.

For example, Grookey's actual height is about 25 pixels, but since the image height is 56, it shrinks down to half the size of the row. On the other hand, Eternatus's Eternamax form takes up the entire 56 pixels, so it's also not possible to simply crop all sprites to half the height in Google Sheets.

Image cropped to actual sprite height (taken from [serebii.net](https://www.serebii.net/pokedex-swsh/icon/810.png)):
Screen Shot 2020-06-15 at 18 45 00
Sprites in 68x56 box:
Screen Shot 2020-06-15 at 18 45 20

### PR DESCRIPTION
**Pull request by martimlobao**
Images were trimmed using ImageMagick, then framed with a 3px transparent border. Contains all images currently in `pokemon-gen8/`. Images came out slightly larger (by an average of 20%) than the originals, despite being trimmed versions. I'm not sure how to fix that, but they're all still extremely small (less than 1.9MB for all 2.6k images) so this isn't a huge deal imo.

Closes #75.

### CODE REVIEW

**Comment by msikma** [comment]
Hi there, thanks for your contribution and sorry for not being able to respond for so long.

The images are probably a little bigger because they haven't gone through pngcrush. There's a script for this in the repo.

One thing is that I'm not 100% sure it's best to keep trimmed versions in this repo—it might be better off in a fork. What are your thoughts about this? The main reason is I'd prefer to keep this repo simple, and adding trimmed versions of only the Gen 8 sprites (and not the older sprites, the items, etc.) seems a bit specific as use case. That way the docs can be made specific to the trimmed images as well, since everything written about e.g. image size no longer applies. Would it be an idea to have a fork that contains only these trimmed sprites, and the data files, and nothing else?

Also, a question, I see you made a commit adding a 3px transparent border, can you explain why it should specifically be 3px?

**Comment by martimlobao** [comment]
No problem, and I completely agree with your point that this might be an overly specific use case. That's also essentially the reason I added the 3px border on the images: when viewing them in Google Sheets, the lack of a transparent border made the images too close together.

With border:
Screen Shot 2020-10-22 at 11 40 09
Without border:
Screen Shot 2020-10-22 at 11 42 29

If you think there's any added value in keeping these images in this repo (I'm probably not the only person using them for Google Sheets), I'd be happy to reorganize them a little (perhaps renaming the folder from `trim` to `sheets` to indicate they work better for that use case), as well as add trimmed versions of every other image in the repo for consistency. Otherwise, I'm perfectly fine with keeping these in a separate fork as well.

Either way, I'll take a look at the png crush script to reduce the image sizes :)

**Comment by JohnEstropia** [comment]
@martimlobao Might be unrelated to this PR, but I see that you have the new Crown Tundra Pokemon in your fork. Do you have a source for the new icons? I've been looking for updated sprites for the pre-CT Pokemon (not just the new ones) as some of them have changed (as reported in https://github.com/msikma/pokesprite/issues/92)

**Comment by martimlobao** [comment]
@JohnEstropia I added them from serebii.net. I think the new versions mentioned in #92 are also there, but since I don't have the shiny versions, I don't want to update them until I have both.

**Comment by JohnEstropia** [comment]
@martimlobao Thanks for your response. It looks like Serebii uses tiny icons for every pokemon except for the updated icons in #92, which are all in the standard sizes we use here in Pokesprite. I guess that works for us for now

**Comment by martimlobao** [comment]
Closing this PR since https://github.com/martimlobao/pokesprite contains trimmed versions under `pokemon-gen8/`

**Pull request closed without merging**
