### PR TITLE
refactor: renamed icons for better veekun/pokedex compatibility

### PR DESCRIPTION
**Pull request by virtuamon**
Related to #39 
There are still many identifiers from the DB that cannot be found as icons (mainly items), but they are mainly aliases of their main icon, which is ok. I added support for most of them via `pkmn.json`, but some of them are tricky to configure because their duplicated is not the main icon, is one of the other forms. 

There was no way to tweak that, so I did something like this, for future reference:
```json
"battle-bond": {
  "is_duplicate": true,
  "is_duplicate_from": "ash"
}
```

but it is still not supported in the generated CSS/spritesheet, causing for example `pkmn-greninja form-battle-bond` to have the regular Greninja icon instead of the Ash one. It would be great if the generator could support that `is_duplicate_from` property or similar.

Here is the list of DB identifiers that are problematic in that sense:

#### Pokemon

* greninja-battle-bond (form-battle-bond == form-ash )
* marowak-totem ( form-totem == form-totem-alola == form-alola )
* meowstic-female ( form-female == gender-female ) -> I cannot find a solution for this case
* raticate-totem-alola ( form-totem == form-totem-alola == form-alola )

#### Items 

Items are more tricky to match because they are grouped by category, so the icon files themselves don't contain the DB name unless the folder name is added as a suffix or prefix (e.g. `ball/beast.png` -> `beast-ball`).

Here is a list of item names from the DB that are not found as icons, they are aliases or they don't have an official icon:

* basement-key--new-mauville
* bridge-mail-d
* bridge-mail-m
* bridge-mail-s
* bridge-mail-t
* bridge-mail-v
* from data-card-01 to data-card-27
* devon-goods
* dna-splicers--merge  (I don't know if there are different sprites for them?)
* dna-splicers--split
* from hm01 to hm08 (tricky because they depend on the type and game)
* from tm01 to tm100 (tricky because they depend on the type and game)
* ilimas-normalium-z
* left-poke-ball
* mega-anchor
* mega-anklet
* mega-glasses
* mega-glove
* mega-pendant
* mega-stickpin
* mega-tiara
* n-lunarizer--merge  (I don't know if there are different sprites for them?)
* n-lunarizer--split
* n-solarizer--merge
* n-solarizer--split
* rm-1-key
* rm-2-key
* rm-4-key
* rm-6-key
* ss-ticket--hoenn
* storage-key
* travel-trunk
* xtranceiver--red (it has a typo in the DB)
* xtranceiver--yellow (it has a typo in the DB)

I also generated a page in my project, to see the full list and what is it matching or what not:
https://capsulemonsters.github.io/pokedex

### CODE REVIEW

**Comment by virtuamon** [comment]
By the way I didn't re-generate the /docs or anything. Should I do it?
Let me know if there are any required config changes or script that I should run.

**Comment by msikma** [comment]
👍 

Will get to work on this when I'm able to.

**Comment by msikma** [comment]
Just wanted to let you know that things are busy and I'm traveling soon, so I'll probably be able to look at this no sooner than April. When I do I'll make sure to look at it properly and do all the necessary testing though.

**Comment by msikma** [comment]
Update: I haven't forgotten about this! 😄

Tomorrow I'm going to look into this.

**Comment by virtuamon** [comment]
@msikma haha it's ok, it's holidays :)

**Comment by msikma** [comment]
I'm working on this now.

My first thought is that the `is_duplicate_from` is a good idea, and in fact it can just replace `is_duplicate` completely. So I'm going to turn all `is_duplicate: true` into `is_duplicate_from: '.'` with the period being code for "the standard icon" in my program.

I've got a question regarding Meowstic. To my knowledge, this is a simple gender difference, like many other Pokémon. But according to your list, it should be a form? I'm curious why that is, because as far as I can tell there's nothing different about Meowstic compared to other Pokémon that have gender differences, like for example Hippopotas. Maybe you could clarify that for me so I know what to do. Is Meowstic an exception that requires `meowstic-female` to be a form identifier?

(Right now the code does not actually permit "female" + "right" to be true at the same time, so I was thinking of changing some code here anyway, even though no icon currently needs both values.)

Regarding items: I see you've left them basically the same except for some renaming. That's fine. Your list raises a few questions:

> Here is a list of item names from the DB that are not found as icons, they are aliases or they don't have an official icon:

I have some of these. Like `bridge-mail-d` is `mail/bridge-m.png`. Or the rm keys. Some of them I don't have, like `data-card-01` although I do have `data-card`. I think these need to be clarified. Do I need to rename or map the ones I do have? What about the ones I don't have? Should I try to find them or do we use placeholders?

**Comment by msikma** [comment]
Made some changes. `is_duplicate` is gone now, replaced by `is_duplicate_from`. (Although maybe I'll rename that to `is_duplicate_of` later... but no big deal for now.) I also changed the code so that it makes use of this new value correctly. So now the Alolan forms are correctly referenced in the build.

screen shot 2018-04-06 at 00 25 58

That's one problem taken care of at least. Let me know your thoughts regarding my questions above.

**Comment by virtuamon** [comment]
Hey thanks for your feedback

About Meowstic, they are more than a cosmetic difference (different abilities and different moveset)
https://www.serebii.net/pokedex-sm/678.shtml
https://www.smogon.com/dex/sm/pokemon/meowstic-f/

I don't know how to solve it code or file-wise. In my opinion it makes more sense to have the file as `meowstic-female` together with `meowstic` and the current female as an alias/duplicate of that form.

For the items, most of them excepting the HM/TMs and the mega- ornaments have an existing image under another similar name, like n-solarizer--merge, n-solarizer--split both are duplicates of n-solarizer.

**Comment by virtuamon** [comment]
@msikma Duplication of individual files doesn't hurt if they don't end up duplicated in the final spritesheet. If you have a mechanism to avoid that then that's great.

> The thing about the images is that I don't have a database for them.

Do you mean the item icons? I can generate from the DB a JSON for you in the same format as the pkm.json. Would that make sense? Then you'll be able to re-use the pkm code also for the items (excepting that they don't have right or female variants)

**Comment by virtuamon** [comment]
I added the items.json file  https://github.com/capsulemonsters/msikma-pokesprite/blob/feature/veekunCompatibility/data/items.json

but I didn't cleaned it up (duplicates, items that don't have any official icon like the mega accessories, etc)

It's generated with this script: [GeneratePokespriteItemsJsonCommand.php](https://github.com/capsulemonsters/pokedex/blob/8bf4ab3b4f56b1dc2de331aea5f0955f8d1dde00/src/core/Console/Commands/GeneratePokespriteItemsJsonCommand.php)

**Comment by msikma** [comment]
Sorry for being absent for so long. I'll put some work in this in the coming week, hopefully then we can finish it.

**Comment by msikma** [comment]
I'm (finally) working on this again! I'll need a little bit more help. There's some stuff missing and some stuff inconsistent between the Veekun database and my files. This is mostly because I haven't retrieved the USUM icons yet. Everything is just SM at the moment. Maybe I can get these icons from your repository somewhere—else I'll go and ask around on IRC.

Here's the full details:

----

My mega items have different names, and I'm missing some. These are the icons in the database:

* `mega-pendant`
* `mega-glasses`
* `mega-glove`
* `mega-anchor`
* `mega-stickpin`
* `mega-tiara`
* `mega-anklet`

The files I have:

* `./icons/key-item/mega-bracelet.png`
* `./icons/key-item/mega-charm.png`
* `./icons/key-item/mega-cuff.png`
* `./icons/key-item/mega-ring.png`

----

For `travel-trunk`, I've got two icons: `travel-trunk--gold.png` and `travel-trunk--silver.png`. The database should contain both of these, right?

----

These appear to be typoed in the database:

* `xtranceiver--red`
* `xtranceiver--yellow`

I've got the following icons, how should we resolve this? Renaming the files is easier, I'm guessing?

* `./icons/key-item/xtransceiver--red.png`
* `./icons/key-item/xtransceiver--yellow.png`

I also have `xtransceiver--blue`, but I assume I should rename this to just `xtransceiver`?

----

There are a few for which I've got partial icons:

* `basement-key`, `basement-key--goldenrod`, `basement-key--new-mauville` - missing the latter.
* `storage-key`, `storage-key--galactic-warehouse`, `storage-key--sea-mauville` - missing the latter.
* `ss-ticket`, `ss-ticket--hoenn` - missing the latter. Is it the old gen 3 icon?
* for the `dna-splicers`, `solarizer` and `lunarizer`, I only have single icons (`dna-splicers.png`, `n-solarizer.png`, `n-lunarizer.png`).

----

Missing:

* `ilimas-normalium-z`
* `left-poke-ball` but it looks identical to the regular pokeball so I suppose I can just copy it.

----

The wonder launcher icons seem to be a bit problematic. I can see that the database contains e.g. `x-sp-atk-6`, `dire-hit-2`, `ability-urge` etc. But...the wonder launcher also has its own versions of regular items, such as revive. And I can only find one revive in the database. This seems wrong - I think the database is missing wonder launcher icons.

On my end, I'm missing all the other data cards. I've only got `data-card.png` in the `key-items` directory, but the database wants 27 of them.

Furthermore there's 100 TMs and 8 HMs. All I have is 4 HMs and all TMs by their type (poison, fighting, etc).

----

Finally, I've got some legacy icons that the database does not have, but that I would like to keep around for compatibility. Probably doesn't matter, I'll just keep them and they will simply not be linked to any item ID.

* `key-item/red-orb-gen3`
* `key-item/card-key-gen3`
* `key-item/secret-key-gen3`
* `key-item/poke-flute-gen3`
* `key-item/red-orb-gen4`
* `key-item/lost-item-mimejr` (I think this comes from gen 3)
* `key-item/dowsing-machine-xy`
* `key-item/dowsing-machine-gen3`
* `key-item/dowsing-machine-gen5`
* `key-item/lock-capsule-gen4`
* `key-item/devon-scope-gen3`
* `key-item/go-goggles-gen3`
* `key-item/town-map-gen3`
* `key-item/blue-orb-gen4`
* `key-item/sparkling-stone-sm`
* `key-item/blue-orb-gen3`
* `etc/unknown-item` (placeholder icon)

----

That's it. So maybe you could help me by giving me your thoughts on the things I mentioned.

Sorry for taking so long with this, stuff just kept coming up constantly. 🙂

If I can get all this sorted out, I can finish the work by updating the JSON file that you generated and link everything to the correct icon files, and then modifying the code to make use of the items file in creating the sprite sheet. That should be easy and quick to do.

**Comment by virtuamon** [comment]
hey sorry for the delay, I am also busy with life and work hehe. Regarding the missing icons:

- All the `mega-` items are in the database but they actually don't have a real icon representation. They can be ignored, deleted from the generated json.
- For the rest they are just typos (transreceiver) or aliases of existing icons like storage-key and basement-key that are different depending on the generation. You can check the file renames I did in this commit https://github.com/msikma/pokesprite/pull/40/commits/e729c4ff98684277df84d03fbf4dd315fddd8c77 , some of them may need to be changed or duplicated
- Keeping gen3 items with the suffix you mention looks good to me
- For the items that don't exist in the database don't worry very much, they could exist in the generated items.json file and we could add them manually.
- HMs are impossible to match since they change types in every game. It's enough to have their type icons.
- Data cards and key items are duplications in the DB.
- For the body icons they are more ui-related but it would still be nice to have them. I think you deleted some of the UI related icons in the past like the mega stone symbol, pokerus, hold item, etc. But I think it's fine to have them. They are more or less consistent between the games.

**Comment by msikma** [comment]
Thanks for the write-up. I'll go finish the last few things then.

**Comment by msikma** [comment]
I've finished generating the JSON file with the items, just need to finish updating the script to utilize it.

**Comment by msikma** [comment]
This took me way too long. Sorry about that. I'm planning to rewrite this repo at some point and make it 100x simpler.

Thanks for your efforts in unifying these various projects.

I hope that the icon format I've used is acceptable for other projects, if not let me know and I'll change it.

**Pull request merged**
