### PR TITLE
Add support for ribbons

### PR DESCRIPTION
**Pull request by msikma**
This adds a [new 'misc' section](https://github.com/msikma/pokesprite/tree/ribbons/misc) for sprites that belong neither to Pokémon nor inventory items.

Included are 109 ribbons from Gen 3-7, but not (yet) the high resolution ones from Gen 8. Gen 3–5 ribbons should be 32x32 (but not all are), and Gen 6–7 40x40. All files and data were processed from [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/List_of_Ribbons_in_the_games) but I messed something up and so not all items have descriptions right now.

Also added is a data file, [`misc.json`](https://github.com/msikma/pokesprite/blob/ribbons/data/misc.json), with entries such as:

```json
{
  "name": {
    "eng": "World Ribbon",
    "jpn": "ワールドリボン",
    "jpn_ro": "World Ribbon"
  },
  "gen": 3,
  "description": {
    "eng": "A Ribbon awarded to a Pokémon League Champion.",
    "gen": 7
  },
  "files": {
    "gen-3": "ribbon/world-ribbon.png"
  }
}
```

The top level `gen` refers to the generation in which the ribbon was first introduced. The `description.gen` refers to what gen a ribbon's description comes from. The `files` object can contain multiple entries and the key indicates what generation a file was ripped from.

If anyone has ideas on how to make this more clear, let me know. Thinking of changing `gen` into `from-gen`, or maybe use `origin-gen` for the top level one.

- [x] Fix missing descriptions for some ribbons
- [x] Resize all Gen 3-5 ribbons to ~32x32~ 40x40
- [x] Add Gen 8 ribbon sprites ~(although I'm not 100% sure if I should since they're much higher resolution)~
- [x] Create docs page

### CODE REVIEW

**Comment by coltongit** [comment]
Looks like some good work that's been done so far. It'll be huge once this is completed and added to pokesprite

**Comment by msikma** [comment]
Question: should the 32x32 ribbons be padded to 40x40? That would make them all the same size. This is a lossless operation since it's an even number of pixels horizontally and vertically. It would simplify building UIs that display ribbons from multiple generations. I'm leaning towards yes myself.

**Comment by koenigderluegner** [comment]
Yes from me for the same reason

**Comment by msikma** [comment]
Changed canvas size for all ribbons to 40x40 and fixed the gamma for Gen 4 and below—ribbons from the older games appeared slightly brighter, but now they're equal.

**Comment by msikma** [comment]
Sorry for lack of progress on this. Planning to have the final things worked out before the weekend.

**Comment by msikma** [comment]
Screenshot 2020-03-18 at 23 48 10

Did some work on the documentation.

**Comment by msikma** [comment]
Looks like it's done to me. I've added the Gen 8 sprites as well, and generated a docs page.

Screenshot 2020-03-21 at 19 06 30

**Comment by msikma** [comment]
I also regenerated the docs page to include ribbons, so you can now view them here: https://msikma.github.io/pokesprite/overview/misc.html

**Pull request merged**
