### PR TITLE
Legends Arceus Pokémon sprites

### PR DESCRIPTION
**Pull request by koenigderluegner**
I added sprites for the new forms and Pokémon of Legends Arceus. It's not the same as what was requested in #116 but was requested in a comment of that issue. The sprites were taken from the [National Pokédex - Icon Dex](https://www.deviantart.com/pikafan2000/art/National-Pokedex-Version-Delta-Icon-Dex-824897934) project and its abundance of collaborators and contributors.

I crushed the images and generated the docs with your scripts.

As a side note: I changed the encoding in your generation script to utf-8 as default, my system (and probably others, i use Windows) doesn't has it as default.

Edit: Forgot to mention, i wasn't able to add japanese slugs since I don't know how to translate them. I added regular noble forms as a fallback to the shiny directory as well.

### CODE REVIEW

**Comment by msikma** [comment]
Wow, this is absolutely incredible work. Thank you! 👍 I'm going to have a look through it and merge it. It looks good to me at first glance. I also saw your other PR on pokesprite-spritesheet. Thanks for your hard work, and I'm sorry that I've been neglecting this project lately. 😞

**Comment by msikma** [comment]
I'll be adding the `jpn` fields and modifying the `jpn_ro` slugs. So far these fields have always been ascii-only, originally since they were meant to be used as CSS class names, even though today you can actually use Unicode for those.

`jpn_ro` contains the official GF romanization of the names which they use for merchandise. I think maybe the official romanizations have not been decided/released yet, as normally these are always without macron characters. For example, エンニュート is "Ennewt" rather than "Ennyūto". This is not a blocker for release of course but it's something to keep in mind, we might need to update this in the future.

**Comment by koenigderluegner** [comment]
>  Thanks for your hard work, and I'm sorry that I've been neglecting this project lately.

Thanks for providing those repos to give me a chance to make PRs :) No need to worry, life happens for all of us.

I don't speak japanse so I had to rely on public sites and mostly "guess" what it could be. Thats why I mentioned it here, I was quite sure this is incorrect how it is now.

If you need anything else let me know

**Comment by msikma** [comment]
I think this is all correct now. I've added Japanese slugs based on past naming conventions. Bulbapedia still shows pure transliterations of the Japanese names, but we know that the Pokémon Company never uses e.g. macron characters in their official romanizations, so I've adjusted them based on that.

Going to merge and renew the docs now.

**Comment by msikma** [comment]
Thanks again for your hard work! I hope I'll have some time for the rest of the updates soon!

**Comment by koenigderluegner** [comment]
I'm glad I could help! This is by far my most used pokemon related project so thanks to you as well :)

**Pull request merged**
