### PR TITLE
Draft: Legends Arceus assets

### LINKED ISSUE #123: [REQUEST] Origin Marks under Misc

### PR DESCRIPTION
**Pull request by koenigderluegner**
Fixes #123

Hello,
I added some Icons from Pokemon Legends Arceus (PLA). 

The images were provided again by [mattyoukhana_](https://twitter.com/mattyoukhana_) on twitter. Much appreciated, as always!

I added origin marks, move mastery, alpha icon, shiny stars and type logos from PLA. As always images are already crushed.

As mentioned in another PR, I am not able to provide japanese translations, so they are missing. 

Also, nearly all icons from this set are plain white, which is very hard to see in the docs, so I added a background to them.

Lastly, some origin marks don't have official names as far as I can tell. According to [Bulbapedia wiki page](https://bulbapedia.bulbagarden.net/wiki/Origin_mark#Types_of_origin_marks) there is no official name, but the german [Pokewiki page](https://www.pokewiki.de/Herkunftssymbol#.C3.9Cbersicht_der_Herkunftssymbole) states, that they are just called after their region. I went with the latter approach, but feel free to apply any changes.

### CODE REVIEW

**Comment by koenigderluegner** [comment]
I added the home variants of the origin marks, I kept the white ones although it seems like they're just recolors. Dark versions were requested in #123. Again, thanks to [mattyoukhana_](https://twitter.com/mattyoukhana_) /  [sora10pls](https://github.com/sora10pls) for providing the resources

**Comment by msikma** [comment]
I added the Japanese text for the new icons. You're right there are no official terms for them but I've just listed the ones people use. Also I thought maybe we could remove "blue" from "(blue) pentagon icon" since that seemed a bit verbose and it's not actually blue anymore anyway.

**Comment by koenigderluegner** [comment]
Totally agree with that pentagon, I omitted the "balck" from black clover, too. I don't really now why i left it there.

**Comment by msikma** [comment]
I'm thinking maybe it would be nice to not hardcode the background color in the json files, but other than that, what do you think still needs to be done before this PR can be considered final?

**Comment by msikma** [comment]
I've changed the script to use a special attribute for all-white sprites instead of having a background color. I do agree with just removing the white icons for PLA though, since they are identical anyway.

Two questions I had. One, should `origin-marks/legends-arceus/sinnoh-gen8.png` be named this considering the others don't have "gen8" in the filename? Does the mark only apply to remake Sinnoh Pokémon and not to original Sinnoh?

Also, this is kind of academic but I figure I'd ask anyway, but the "origin" value was originally used to indicate "this gen is where this image came from", not "this gen is where this concept first appeared". Its use is mainly to distinguish multiple images for the same thing from different gens. So by that measure I think all the images in "origin marks" should be Gen 7 or Gen 8 if I'm not mistaken, and "shiny stars" should be Gen 8 I think, am I correct?

**Comment by koenigderluegner** [comment]
> I do agree with just removing the white icons for PLA though, since they are identical anyway.

Absolutely fine by me.

> Does the mark only apply to remake Sinnoh Pokémon and not to original Sinnoh?

Yes, all games before Gen 6 don't have a mark at all (exception Gen 1/2 from Virtual Console, but they were released afterwards).

> So by that measure I think all the images in "origin marks" should be Gen 7 or Gen 8 if I'm not mistaken, and "shiny stars" should be Gen 8 I think, am I correct?

That is correct, it seems like I misunderstood how the table was built. 

image

In this image, origin seems to be "first time of appearance" and filename/gen the source it was taken from.

Actually can't remember which style I've chosen, but feel free to change :)

**Comment by msikma** [comment]
> In this image, origin seems to be "first time of appearance" and filename/gen the source it was taken from.

I've actually managed to confuse myself with this despite being the one who came up with that, lol

It doesn't really matter too much, it's just a piece of metadata. So I guess the middle "gen" is "where this concept was first introduced" and the second gen is "where this image is from".

**Comment by msikma** [comment]
Thanks again for your work. I've thought about the whole "gen" discussion some more but it's fine the way it is. Also, I've decided to just leave the Legends Arceus origin marks in even though they're the same, just so people don't look at their absence and think "is this missing?" It doesn't hurt to have them there.

**Comment by koenigderluegner** [comment]
I'm glad i could help! Sounds good to me, maybe we can clear things up when Scarlet/Violet arrive :P

**Pull request merged**
