### PR TITLE
HOME 2.0.0 update ball sprites

### LINKED ISSUE #121: Pixel Sprites for Hisui Balls dumped from HOME
FTAMoqPXoAMmlOH
Pokémon HOME introduced new sprites for the ancient Hisui balls for Pokémon Legends Arceus, and the dump was from @mattyoukhana_ on Twitter, although before they get added we'll have to wait until matt gives us a new image to work with since the image in question has what seems to be a little bit of jpg artifacting (non-white pixels can be seen in the white borders around the balls). I'm also hoping this isn't what the base image file looks like either. Apologies if any of this looks unprofessional, I don't use GitHub but wanted to contribute to this.

### PR DESCRIPTION
**Pull request by koenigderluegner**
Fixes https://github.com/msikma/pokesprite/issues/121 

I've added the ball sprites which were introduced with the HOME 2.0.0 update.

Icons were provided by [mattyoukhana_](https://twitter.com/mattyoukhana_) on twitter (see [tweet](https://twitter.com/mattyoukhana_/status/1527086894877749250)), much appreciated.

Things to notice: Original size of the icons is 64x64, so I had to resize them. These icons had more details than older icons, this level of detail got lost due to the resizing. They still look very good as far as I can tell but might be worth to give it another look. 
Also: The filenames had a "^o"-suffix, I'm not sure if this was an import error or some new way how they handle item names. For now I kept it like I got them.

As a small bonus: I fixed some errors/deprecated code in the gen script, so my (and possibly other) IDEs throw far less errors.

### CODE REVIEW

**Comment by msikma** [comment]
Thank you! As always I appreciate your help with the project. I'm also not entirely sure about the `^o` thing. Maybe it's to indicate the outline? Since these don't seem to conflict with existing IDs maybe we can just remove that.

I'll have a closer look later today.

**Comment by msikma** [comment]
Just wanted to let you know that I haven't forgotten about this. It's just that life has been really incredibly busy lately and I'm in the process of getting a new job, so I haven't been able to get to it yet. But I hope to be able to do it this weekend!

**Comment by koenigderluegner** [comment]
Thanks for letting us know! I hope your switch doesn't bring any problems with it, so good luck on that! I might have another PR by then, but it requires translation into japanese, which i can't do myself. Is that something you could do, asking in general?

**Comment by msikma** [comment]
Absolutely, feel free to leave Japanese related things blank and I'll do them.

**Comment by msikma** [comment]
Sorry for being late in merging this. I'm going to have a look at your other PR now.

**Pull request merged**
